name: 'dbt_tags_test'
version: '0.0.0'
config-version: 2

profile: 'dbt_tags'

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

on-run-start:
  - > # re-create common schema
    {% if var("fresh", false) %}
      create or replace schema {{ dbt_tags.get_resource_ns() }};
    {% endif %}
on-run-end:
  - >
    {% if flags.WHICH in ('run', 'build') %}
      {{ dbt_tags.apply_source_column_tags() }}
    {% endif %}

vars:
  dbt_tags__tag_source_columns: true
  dbt_tags__database: dbt_tags
  dbt_tags__schema: common
  dbt_tags__resource_types: ["model", "snapshot", "source"]
  dbt_tags__allowed_tags:
    - pii_name
    - pii_amount
    - pii_null
    - abc
  dbt_tags__policy_data_types:
    - pii_null: ['varchar','number']

models:
  dbt_tags_test:
    post-hook:
      - >
        {% if flags.WHICH in ('run', 'build') %}
          {{ dbt_tags.apply_column_tags() }}
        {% endif %}

seeds:
  dbt_tags_test:
    +schema: raw
