name: testing on pull request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  snowflake:
    runs-on: ubuntu-latest
    env:
      DBT_SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_TEST_ACCOUNT }}
      DBT_SNOWFLAKE_TEST_USER: ${{ secrets.DBT_SNOWFLAKE_TEST_USER }}
      DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD: ${{ secrets.DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD }}
      DBT_SNOWFLAKE_TEST_ROLE: ${{ secrets.DBT_SNOWFLAKE_TEST_ROLE }}
      DBT_SNOWFLAKE_TEST_DATABASE: ${{ secrets.DBT_SNOWFLAKE_TEST_DATABASE }}
      DBT_SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_TEST_WAREHOUSE }}
      DBT_SCHEMA: PRCI_${{ github.sha }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.7.1

      - name: Install dependencies
        run: |
          poetry config installer.max-workers 1
          poetry config virtualenvs.in-project true
          poetry install
          mkdir ~/.dbt
          cp integration_tests/ci/ci.profiles.yml ~/.dbt/profiles.yml

      - name: Code Quality
        run: |
          poetry run poe lint

      - name: Test dbt tags
        run: |
          poetry run poe dbt-tags-test
